apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-jupyter-nb-pvc
  namespace: jupyter-nb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 30Gi