apiVersion: v1
kind: Service
metadata:
  name: jupyter-nb-service
  namespace: jupyter-nb
spec:
  selector:
    app: jupyter-nb
  type: LoadBalancer
  ports:
    - name: jupyter-nb-port
      protocol: TCP
      port: 8888
      targetPort: 8888
  loadBalancerIP: 10.0.0.222